/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package flow;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class AppTest {
    @Test void appHasAGreeting() {
        App classUnderTest = new App();
        assertNotNull(classUnderTest.getGreeting(), "app should have a greeting");
    }
@Test void testSumar(){
    App classUnderTest = new App();
    assertEquals(5, classUnderTest.sumar(2, 3));

}
@Test void testResta(){
    App classUnderTest = new App();
    assertEquals(2, classUnderTest.sumar(4, 2));

}


    

}
